# Generated by Django 5.2.11 on 2026-02-20 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_id', models.IntegerField()),
                ('order_type', models.CharField(choices=[('Addon', 'Addon'), ('Package', 'Package')], default='Addon', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accommodation', models.CharField(blank=True, max_length=255)),
                ('accommodation_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('accommodation_days', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appointment_type', models.CharField(choices=[('Walkin', 'Walk-in'), ('Telephonic', 'Telephonic'), ('Online', 'Online')], default='Walkin', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Insurance', 'Insurance')], default='Pending', max_length=20)),
                ('payment_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.city')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.doctor')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.hotel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.treatment')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='appointments.appointment')),
                ('diet_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.dietitem')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=50)),
                ('pulse', models.CharField(blank=True, max_length=50)),
                ('temperature', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('respiratory_rate', models.CharField(blank=True, max_length=50)),
                ('spo2', models.CharField(blank=True, max_length=50)),
                ('general_appearance', models.TextField(blank=True)),
                ('skin', models.TextField(blank=True)),
                ('tongue', models.TextField(blank=True)),
                ('nails', models.TextField(blank=True)),
                ('eyes', models.TextField(blank=True)),
                ('appetite', models.TextField(blank=True)),
                ('digestion', models.TextField(blank=True)),
                ('bowel', models.TextField(blank=True)),
                ('urination', models.TextField(blank=True)),
                ('sleep_quality', models.TextField(blank=True)),
                ('perspiration', models.TextField(blank=True)),
                ('prakriti', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatments_prescribed', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='appointments.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='PackageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('activity', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('addon_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.addonorder')),
            ],
            options={
                'ordering': ['schedule_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('present_complaints', models.TextField(blank=True)),
                ('history_present_complaints', models.TextField(blank=True)),
                ('past_illness', models.TextField(blank=True)),
                ('history_past_illness', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True)),
                ('stress_level', models.CharField(blank=True, max_length=50)),
                ('habits', models.TextField(blank=True)),
                ('sleep', models.CharField(blank=True, max_length=100)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
